add: gh workflow to keep server alive
metakgp/mftp pull request #45
Opened 2022-10-08 11:54 UTC by nilesh05apr

Switch From Ping Mechanism To Heroku Scheduler #38

Added github actions workflow to solve the issue. scheduled a cron job for every 10 minute which sends curl request to https://mftp.herokuapp.com/

2022-10-08 13:37 UTC, thealphadollar requested changes

2022-10-08 13:37 UTC, thealphadollar commented on .github/workflows/ping.yml
> +        run: curl -X GET https://mftp.herokuapp.com/
```suggestion
        run: curl mftp.herokuapp.com -o NUL
```

Do you think we should use the original command, as it is from the script?

2022-10-08 13:53 UTC, thealphadollar approved these changes

2023-09-20 13:43 UTC, proffapt commented
Closing this, because:

- Heroku is and will not be used anymore: Paid, and we have a free solution.
- And, https://github.com/metakgp/mftp/pull/62

2023-09-20 13:43 UTC, closed without merging